// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using PoliScrum.Models;

namespace PoliScrum.Migrations
{
    [DbContext(typeof(PoliScrumContext))]
    [Migration("20190506221809_Migracion5")]
    partial class Migracion5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("PoliScrum.Models.Proyecto", b =>
                {
                    b.Property<int>("ProyectoId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Estado");

                    b.Property<DateTime>("FechaFin");

                    b.Property<DateTime>("FechaFinEstimada");

                    b.Property<DateTime>("FechaInicio");

                    b.Property<string>("Nombre")
                        .HasMaxLength(200);

                    b.HasKey("ProyectoId");

                    b.ToTable("PST_PROYECTOS");
                });

            modelBuilder.Entity("PoliScrum.Models.UserStory", b =>
                {
                    b.Property<int>("UserStoryId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CriteriosAceptacion")
                        .HasMaxLength(4000);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(4000);

                    b.Property<int>("DuracionEstimada");

                    b.Property<DateTime>("FechaFin");

                    b.Property<DateTime>("FechaInicio");

                    b.Property<int>("OrdenPrioridad");

                    b.Property<string>("Titulo")
                        .HasMaxLength(200);

                    b.Property<int>("Valor");

                    b.HasKey("UserStoryId");

                    b.ToTable("PST_USER_STORIES");
                });
#pragma warning restore 612, 618
        }
    }
}
