// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using PoliScrum.Models;

namespace PoliScrum.Migrations
{
    [DbContext(typeof(PoliScrumContext))]
    partial class PoliScrumContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("PoliScrum.Models.EstadoProyecto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Activo");

                    b.Property<string>("Descripcion");

                    b.HasKey("ID");

                    b.ToTable("ProyectoEstados");
                });

            modelBuilder.Entity("PoliScrum.Models.HistoriaUsuario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CriterioAceptacion");

                    b.Property<string>("Descripcion");

                    b.Property<int>("DuracionEstimada");

                    b.Property<int?>("IDProductBacklogID");

                    b.Property<int>("Orden");

                    b.Property<int>("Valor");

                    b.Property<string>("titulo");

                    b.HasKey("ID");

                    b.HasIndex("IDProductBacklogID");

                    b.ToTable("UserStories");
                });

            modelBuilder.Entity("PoliScrum.Models.ProductBacklog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("FechaCreacion");

                    b.Property<int?>("IDProyectoID");

                    b.Property<int?>("IDUsuarioResponsableID");

                    b.HasKey("ID");

                    b.HasIndex("IDProyectoID");

                    b.HasIndex("IDUsuarioResponsableID");

                    b.ToTable("ProductBacklogs");
                });

            modelBuilder.Entity("PoliScrum.Models.Proyecto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("EstadoID");

                    b.Property<DateTime>("FechaFin");

                    b.Property<DateTime>("FechaFinEstimado");

                    b.Property<DateTime>("FechaInicio");

                    b.Property<string>("Nombre");

                    b.HasKey("ID");

                    b.HasIndex("EstadoID");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("PoliScrum.Models.Rol", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Activo");

                    b.Property<string>("Descripcion");

                    b.HasKey("ID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("PoliScrum.Models.Usuario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellido")
                        .HasMaxLength(100);

                    b.Property<string>("Cedula")
                        .HasMaxLength(30);

                    b.Property<string>("Contrasena")
                        .HasMaxLength(100);

                    b.Property<string>("CorreoElectronico")
                        .HasMaxLength(100);

                    b.Property<DateTime>("FechaNacimiento");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100);

                    b.HasKey("ID");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PoliScrum.Models.HistoriaUsuario", b =>
                {
                    b.HasOne("PoliScrum.Models.ProductBacklog", "IDProductBacklog")
                        .WithMany()
                        .HasForeignKey("IDProductBacklogID");
                });

            modelBuilder.Entity("PoliScrum.Models.ProductBacklog", b =>
                {
                    b.HasOne("PoliScrum.Models.Proyecto", "IDProyecto")
                        .WithMany()
                        .HasForeignKey("IDProyectoID");

                    b.HasOne("PoliScrum.Models.Usuario", "IDUsuarioResponsable")
                        .WithMany()
                        .HasForeignKey("IDUsuarioResponsableID");
                });

            modelBuilder.Entity("PoliScrum.Models.Proyecto", b =>
                {
                    b.HasOne("PoliScrum.Models.EstadoProyecto", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoID");
                });
#pragma warning restore 612, 618
        }
    }
}
